build:
  cuda_version: "12.1.1"
  python_packages:
    - accelerate==1.8.1
    - transformers==4.53.0
    - vllm==0.9.1
    - tokenizers==0.21.2
    - pydantic==2.11.7
    - inferless==0.2.15
    - hf_transfer==0.1.9
